### ISSUE TITLE
Extension does not compile with latest Ninject version from master

### ISSUE THREAD

**Issue by sglienke** [ninject/Ninject.Extensions.Factory#30]
The issue is that in the private method `ToFactory` in `BindToExtensions` syntax.Kernel is accessed. `IBindingToSyntax<T>` does not have the member Kernel (I guess that was removed during the ReadOnlyKernel refactoring?).

Is there any other way to access the current IBindingRoot in that method?

**Comment by scott-xu** [comment]
PR is welcome

**Comment by sglienke** [comment]
I would submit one if I had a clue how to solve it :)

As far as I can see a `IBindingToSyntax<T>` has no reference anymore to the bindingroot that is required to add another binding. But it could be that I am missing something.

**Comment by scott-xu** [comment]
ReadOnlyKernel is backed out.
