### ISSUE TITLE
Silverlight 3.0 is not supported

### ISSUE THREAD

**Issue by googol** [ninject/Ninject.Extensions.Factory#34]
Hi,

just wanted to let you guys know your library doesn't support silverlight 3.0 since 2012 (commit 9859017a3e00d230f906ba9183362776e26bf60e) because of Castle.Core losing support for the platform.
It would be nice to not have it look like the platform is supported. The commit I referenced renamed the SL4 Castle.Core libs to be the SL3, which obviously doesn't work.

**Comment by scott-xu** [comment]
Since 3.3, Ninject dropped SL platform
