### ISSUE TITLE
troubles with adaptation Ninject.Extensions.Factory for .Net Core

### ISSUE THREAD

**Issue by lsoft** [ninject/Ninject.Extensions.Factory#35]
At first, I adapted Ninject 3.2.3 for .Net Core. All Ninject tests passed green. Looks like there is no problem.
Next I adapted Ninject.Extensions.Factory for .Net Core. It compiles but Ninject.Extensions.Factory.Test fails.

Easiest example:

Running test Ninject.Extensions.Factory.FactoryTests.SingleBinding...
[xUnit.net 00:00:00.7008458]   Starting:    Ninject.Extensions.Factory.Test
[xUnit.net 00:00:01.1343741]     Ninject.Extensions.Factory.FactoryTests.SingleBindingWhenUsingNineGenericBind [FAIL]
[xUnit.net 00:00:01.1361869]       Ninject.ActivationException : **Error activating IInterceptor using conditional implicit self-binding of IInterceptor**
[xUnit.net 00:00:01.1363763]       Provider returned null.
[xUnit.net 00:00:01.1365367]       Activation path:
[xUnit.net 00:00:01.1367484]         2) Injection of dependency IInterceptor into parameter  of constructor of type IWeaponFactoryProxy
[xUnit.net 00:00:01.1368207]         1) Request for IWeaponFactory
[xUnit.net 00:00:01.1368955]       
[xUnit.net 00:00:01.1369682]       Suggestions:
[xUnit.net 00:00:01.1370610]         1) Ensure that the provider handles creation requests properly.
[xUnit.net 00:00:01.1371871]       
[xUnit.net 00:00:01.1387702]       Stack Trace:
[xUnit.net 00:00:01.1407027]         c:\projects\git\Ninject\!Ninject 3.2.3 NetCore Working\Ninject\Activation\Context.cs(186,0): at Ninject.Activation.Context.ResolveInternal(Object scope)
[xUnit.net 00:00:01.1412330]         c:\projects\git\Ninject\!Ninject 3.2.3 NetCore Working\Ninject\Activation\Context.cs(160,0): at Ninject.Activation.Context.Resolve()
[xUnit.net 00:00:01.1413707]         c:\projects\git\Ninject\!Ninject 3.2.3 NetCore Working\Ninject\KernelBase.cs(400,0): at Ninject.KernelBase.<>c__DisplayClass30_0.<Resolve>b__4(IBinding binding)
[xUnit.net 00:00:01.1415982]            at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
[xUnit.net 00:00:01.1417209]            at System.Linq.Enumerable.<CastIterator>d__35`1.MoveNext()
[xUnit.net 00:00:01.1418372]            at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
[xUnit.net 00:00:01.1419433]            at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
[xUnit.net 00:00:01.1420609]            at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
[xUnit.net 00:00:01.1675591]     Ninject.Extensions.Factory.FactoryTests.SingleBinding [FAIL]
[xUnit.net 00:00:01.1677361]       Ninject.ActivationException : Error activating IInterceptor using conditional implicit self-binding of IInterceptor
[xUnit.net 00:00:01.1678101]       Provider returned null.
[xUnit.net 00:00:01.1678507]       Activation path:
[xUnit.net 00:00:01.1678918]         2) Injection of dependency IInterceptor into parameter  of constructor of type IWeaponFactoryProxy
[xUnit.net 00:00:01.1679713]         1) Request for IWeaponFactory
[xUnit.net 00:00:01.1680517]       
[xUnit.net 00:00:01.1681176]       Suggestions:
[xUnit.net 00:00:01.1681877]         1) Ensure that the provider handles creation requests properly.
[xUnit.net 00:00:01.1682377]       
[xUnit.net 00:00:01.1683019]       Stack Trace:
[xUnit.net 00:00:01.1684114]         c:\projects\git\Ninject\!Ninject 3.2.3 NetCore Working\Ninject\Activation\Context.cs(186,0): at Ninject.Activation.Context.ResolveInternal(Object scope)
[xUnit.net 00:00:01.1686055]         c:\projects\git\Ninject\!Ninject 3.2.3 NetCore Working\Ninject\Activation\Context.cs(160,0): at Ninject.Activation.Context.Resolve()
[xUnit.net 00:00:01.1687210]         c:\projects\git\Ninject\!Ninject 3.2.3 NetCore Working\Ninject\KernelBase.cs(400,0): at Ninject.KernelBase.<>c__DisplayClass30_0.<Resolve>b__4(IBinding binding)
[xUnit.net 00:00:01.1688993]            at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
[xUnit.net 00:00:01.1689989]            at System.Linq.Enumerable.<CastIterator>d__35`1.MoveNext()
[xUnit.net 00:00:01.1691058]            at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
[xUnit.net 00:00:01.1691738]            at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
[xUnit.net 00:00:01.1692786]            at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
[xUnit.net 00:00:01.1734806]   Finished:    Ninject.Extensions.Factory.Test
Test failed 

Ninject and its plugins is complicated so I am unable to fix this issue by myself. Please help.

**Visual Studio Code** solution here: https://www.dropbox.com/s/gi3jf0facgzlgvv/Example.zip?dl=0
I am using VS Code 1.12.2 on Windows. VS code extensions:
- C# for Visual Studio Code (powered by OmniSharp)
- Nuget package manager

Target framework is netcoreapp1.1.

PTR:
1) Open the solution in VS Code
2) Press Ctrl+` to open terminal
3) Execute
  dotnet restore .\Ninject.Extensions.Factory.Test\Ninject.Extensions.Factory.Test.csproj
  dotnet build  .\Ninject.Extensions.Factory.Test\Ninject.Extensions.Factory.Test.csproj
4) open FactoryTests.cs file, find SingleBinding test and press "run test" nearby the test's name
OR
execute
  dotnet test  .\Ninject.Extensions.Factory.Test\Ninject.Extensions.Factory.Test.csproj
to run all tests. There are 43 failed test at all (120 total).

Any help/ideas/suggestions?

**Comment by TheOneSock** [comment]
I'm a beginner at this, but I noticed you are missing bindings specified in  FuncModule

```
 public override void Load()
        {
            if (!this.Kernel.GetBindings(typeof(Func<IContext, IResolutionRoot>)).Any())
            {
                this.Bind<Func<IContext, IResolutionRoot>>().ToMethod(ctx => context => context.Kernel);
            }

            this.Bind<FuncProvider>().ToSelf().InSingletonScope();
            this.Bind<IFunctionFactory>().To<FunctionFactory>();
            this.Bind<IInstanceProvider>().To<StandardInstanceProvider>();
#if !SILVERLIGHT_20 && !WINDOWS_PHONE && !NETCF_35
            this.Bind<IInterceptor>().To<FactoryInterceptor>()
                .When(request => typeof(IFactoryProxy).IsAssignableFrom(request.Target.Member.ReflectedType()));
#endif

            this.Bind(typeof(Func<>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,>)).ToProvider<FuncProvider>();
#if !NET_35 && !SILVERLIGHT_30 && !SILVERLIGHT_20 && !WINDOWS_PHONE && !NETCF_35
            this.Bind(typeof(Func<,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,,,,,,,>)).ToProvider<FuncProvider>();
#endif
        }
```

so removing all preprocessor directives like so:


 ```
public class FuncModule : NinjectModule
    {
        /// <summary>
        /// Loads the module into the kernel.
        /// </summary>
        public override void Load()
        {
            if (!this.Kernel.GetBindings(typeof(Func<IContext, IResolutionRoot>)).Any())
            {
                this.Bind<Func<IContext, IResolutionRoot>>().ToMethod(ctx => context => context.Kernel);
            }

            this.Bind<FuncProvider>().ToSelf().InSingletonScope();
            this.Bind<IFunctionFactory>().To<FunctionFactory>();
            this.Bind<IInstanceProvider>().To<StandardInstanceProvider>();

            this.Bind<IInterceptor>().To<FactoryInterceptor>()
                .When(request => typeof(IFactoryProxy).IsAssignableFrom(request.Target.Member.ReflectedType()));


            this.Bind(typeof(Func<>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,,,,,,>)).ToProvider<FuncProvider>();
            this.Bind(typeof(Func<,,,,,,,,,,,,,,,,>)).ToProvider<FuncProvider>();
        }
    }
```

**Comment by lsoft** [comment]
TheOneSock
thank you! you are right.

1st failing test is FuncTests.LazyInjection
```
[xUnit.net 00:00:00.9723007]       Ninject.ActivationException : Error activating Lazy{IWeapon} using implicit self-binding of Lazy{IWeapon}
[xUnit.net 00:00:00.9724795]       Several constructors have the same priority. Please specify the constructor using ToConstructor syntax or add an Inject attribute.
[xUnit.net 00:00:00.9725487]       
[xUnit.net 00:00:00.9725851]       Constructors:
[xUnit.net 00:00:00.9726236]       Lazy`1(IWeapon value)
[xUnit.net 00:00:00.9726890]       Lazy`1(Func{IWeapon} valueFactory)
[xUnit.net 00:00:00.9728494]       
[xUnit.net 00:00:00.9729328]       Activation path:
[xUnit.net 00:00:00.9730183]         2) Injection of dependency Lazy{IWeapon} into parameter lazyWeapon of constructor of type ClassWithLazy
[xUnit.net 00:00:00.9731047]         1) Request for ClassWithLazy
[xUnit.net 00:00:00.9731863]       
[xUnit.net 00:00:00.9732578]       Suggestions:
[xUnit.net 00:00:00.9733305]         1) Ensure that the implementation type has a public constructor.
[xUnit.net 00:00:00.9734194]         2) If you have implemented the Singleton pattern, use a binding with InSingletonScope() instead.
```
it looks like we can manage this problem (at least in theory). I'm planning to look at this in the coming days.

2nd failing test is FactoryInterceptorTests.Intercept
```
[xUnit.net 00:00:01.1420254]     Ninject.Extensions.Factory.UnitTests.FactoryInterceptorTests.Intercept [FAIL]
[xUnit.net 00:00:01.1441135]       System.Runtime.InteropServices.COMException : Could not find a CA property. (Exception from HRESULT: 0x8013144D)
[xUnit.net 00:00:01.1455944]       Stack Trace:
[xUnit.net 00:00:01.1476552]            at System.Reflection.PseudoCustomAttribute._GetSecurityAttributes(RuntimeModule module, Int32 token, Boolean assembly, Object[]& securityAttributes)
[xUnit.net 00:00:01.1480170]            at System.Reflection.PseudoCustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean includeSecCa, Int32& count)
[xUnit.net 00:00:01.1482197]            at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeMethodInfo target)
[xUnit.net 00:00:01.1483394]            at Castle.DynamicProxy.Internal.AttributeUtil.<GetNonInheritableAttributes>d__5.MoveNext()
[xUnit.net 00:00:01.1484703]            at Castle.DynamicProxy.Contributors.CompositeTypeContributor.ImplementMethod(MetaMethod method, ClassEmitter class, ProxyGenerationOptions options, OverrideMethodDelegate overrideMethod)
[xUnit.net 00:00:01.1486662]            at Castle.DynamicProxy.Contributors.CompositeTypeContributor.Generate(ClassEmitter class, ProxyGenerationOptions options)
[xUnit.net 00:00:01.1487786]            at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateType(String name, Type[] interfaces, INamingScope namingScope)
[xUnit.net 00:00:01.1488860]            at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
[xUnit.net 00:00:01.1490219]            at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
[xUnit.net 00:00:01.1492178]            at Moq.Proxy.CastleProxyFactory.CreateProxy(Type mockType, ICallInterceptor interceptor, Type[] interfaces, Object[] arguments)
[xUnit.net 00:00:01.1492858]            at Moq.Mock`1.<InitializeInstance>b__19_0()
[xUnit.net 00:00:01.1493705]            at Moq.Mock`1.OnGetObject()
[xUnit.net 00:00:01.1494573]            at Moq.MockDefaultValueProvider.ProvideDefault(MethodInfo member)
[xUnit.net 00:00:01.1495646]            at Moq.HandleMockRecursion.HandleIntercept(ICallContext invocation, InterceptorContext ctx, CurrentInterceptContext localctx)
[xUnit.net 00:00:01.1496643]            at Moq.Interceptor.Intercept(ICallContext invocation)
[xUnit.net 00:00:01.1497600]            at Castle.DynamicProxy.AbstractInvocation.Proceed()
[xUnit.net 00:00:01.1498520]            at Castle.Proxies.ObjectProxy_2.get_Method()
[xUnit.net 00:00:01.1499508]            at Moq.MatcherFactory.CreateMatcher(Expression expression, Boolean isParams)
[xUnit.net 00:00:01.1500611]            at Moq.MethodCall..ctor(Mock mock, Condition condition, Expression originalExpression, MethodInfo method, Expression[] arguments)
[xUnit.net 00:00:01.1501753]            at Moq.MethodCallReturn`2..ctor(Mock mock, Condition condition, Expression originalExpression, MethodInfo method, Expression[] arguments)
[xUnit.net 00:00:01.1502929]            at Moq.Mock.<>c__DisplayClass62_0`2.<Setup>b__0()
```

soooo..... :) probably it's not a Ninject issue.... I have no ideas how to handle this at all...

Yeah, we can remove this tests , but it's a "Dark side of the Force", Luke :)

**Comment by lsoft** [comment]
Additionaly... I'm looking around NO_ASSEMBLY_SCANNING macro... it completely depends on appdomains, assemblies etc... so it's impossible to adapt it to .net core 1.
but I've implemented a fake assembly scanner (NetCoreFakeAssemblyNameRetriever) and now there is no need to manually write 
```
kernel.Load(new FuncModule());
```

fake scanner makes Ninject.Extensions.Factory.dll to be scanned for ninject modules, so FuncModule will be found and loaded automatically.

https://www.dropbox.com/s/nvv3levw695o81b/ninject%20netcore%20%282%20failing%20tests%29.zip?dl=0

**Comment by lsoft** [comment]
ok, I've shed some light on FuncTests.LazyInjection. 

Lazy< T > declares as 

```
#region Assembly System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// System.Runtime.dll
#endregion

using System.Threading;

namespace System
{
    public class Lazy<T>
    {
        public Lazy();
        public Lazy(bool isThreadSafe);
        public Lazy(Func<T> valueFactory);
        public Lazy(LazyThreadSafetyMode mode);
        public Lazy(Func<T> valueFactory, bool isThreadSafe);
        public Lazy(Func<T> valueFactory, LazyThreadSafetyMode mode);

        public bool IsValueCreated { get; }
        public T Value { get; }

        public override string ToString();
    }
}

```

(note there are 6 constructors)

but this code

```
            var t = typeof(Lazy<IWeapon>);
            var cs = t.GetConstructors();

```

returns SEVEN constructors, with one additional:


`Void .ctor(Ninject.Extensions.Factory.Fakes.IWeapon)
`

(.Net framework returns 6 constructors as declared)

It produces a trouble with StandardConstructorScorer, 2 constructors 

```
Void .ctor(Ninject.Extensions.Factory.Fakes.IWeapon)
Void .ctor(System.Func`1[Ninject.Extensions.Factory.Fakes.IWeapon])

```

scored same, so Ninject cannot choose a constructor and raised ConstructorsAmbiguous exception.

No idea how to resolve it best. Probably, easiest way is to remove this test and mark that Lazy< T > does not supported.

**Comment by lsoft** [comment]
I've disabled both tests.
Additional I've found one more problem with ninject (not ninject.factory extension) unit test. Ninject.Tests.Integration.ConstructorArgumentTests.ConstructorArgumentsArePassedToFirstLevel fails with probability about 20%:

```
[xUnit.net 00:00:00.7385346]   Discovering: Ninject.Test
[xUnit.net 00:00:01.3521090]   Discovered:  Ninject.Test
[xUnit.net 00:00:01.5359547]   Starting:    Ninject.Test
[xUnit.net 00:00:03.3371465]     Ninject.Tests.Integration.ConstructorArgumentTests.ConstructorArgumentsArePassedToFirstLevel(constructorArgument: Func`2 { Method = Ninject.
Parameters.IConstructorArgument <get_ConstructorArguments>b__3_1(Boolean), Target = <>c { } }) [FAIL]
[xUnit.net 00:00:03.3386659]       Expected type to be Ninject.Tests.Fakes.Sword, but found <null>.
[xUnit.net 00:00:03.3400416]       Stack Trace:
[xUnit.net 00:00:03.3413763]         C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs(32,0): at FluentAssertions.Execution.XUni
t2TestFramework.Throw(String message)
[xUnit.net 00:00:03.3416953]         C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs(197,0): at FluentAssertions.Execution.AssertionScope.FailWith(St
ring message, Object[] args)
[xUnit.net 00:00:03.3420639]         C:\projects\fluentassertions-vf06b\Src\Core\Primitives\ReferenceTypeAssertions.cs(138,0): at FluentAssertions.Primitives.ReferenceTypeAs
sertions`2.BeOfType(Type expectedType, String because, Object[] becauseArgs)
[xUnit.net 00:00:03.3422871]         C:\projects\fluentassertions-vf06b\Src\Core\Primitives\ReferenceTypeAssertions.cs(120,0): at FluentAssertions.Primitives.ReferenceTypeAs
sertions`2.BeOfType[T](String because, Object[] becauseArgs)
[xUnit.net 00:00:03.3424744]         C:\projects\git\Ninject\!Ninject 3.2.3 NetCore Working\Ninject.Test\Integration\ConstructorArgumentTests.cs(84,0): at Ninject.Tests.Inte
gration.ConstructorArgumentTests.ConstructorArgumentsArePassedToFirstLevel(Func`2 constructorArgument)
[xUnit.net 00:00:03.3476988]   Finished:    Ninject.Test
Не пройдено:  Ninject.Tests.Integration.ConstructorArgumentTests.ConstructorArgumentsArePassedToFirstLevel(constructorArgument: Func`2 { Method = Ninject.Parameters.IConstru
ctorArgument <get_ConstructorArguments>b__3_1(Boolean), Target = <>c { } })
Сообщение об ошибке:
 Expected type to be Ninject.Tests.Fakes.Sword, but found <null>.
Трассировка стека:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:
line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.BeOfType(Type expectedType, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\
Primitives\ReferenceTypeAssertions.cs:line 138
   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.BeOfType[T](String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\Refer
enceTypeAssertions.cs:line 120
   at Ninject.Tests.Integration.ConstructorArgumentTests.ConstructorArgumentsArePassedToFirstLevel(Func`2 constructorArgument) in C:\projects\git\Ninject\!Ninject 3.2.3 NetC
ore Working\Ninject.Test\Integration\ConstructorArgumentTests.cs:line 84

```

It fails only by run through

`dotnet test .\Ninject.Test\Ninject.Test.csproj`

Running only this test without the rest   gives the green light all the time. Magic! :) (probably, black magic)

Let's mark the finish line.
**For me** looks like Ninject project is abandoned by its maintainers. So there not much sense to spend a lot of time to resolve adaptation problems without any support from the maintainers. 
Last version of my adaptation can be downloaded from

https://www.dropbox.com/s/2j5j59nch47zwss/Ninject%203.2.3%20NetCore.zip?dl=0

(Visual Studio Code, .net core 1)


But I think it's risky to use it in a production environment.

**Comment by scott-xu** [comment]
Please try 3.3.0

**Comment by lsoft** [comment]
@scott-xu

While I adapted Ninject to .net core 1/2 for myself I faced with problems related with WeakReference and GC, AssemblyScanner, Func constructors etc.

For example:

    Failed:  Ninject.Tests.Unit.ActivationCacheTests.DeadObjectsAreRemoved
    Error message:
     Expected value to be 0, but found 1.
    Stack trace:
       at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
       at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
       at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[] becauseArgs)
       at Ninject.Tests.Unit.ActivationCacheTests.DeadObjectsAreRemoved() in     C:\projects\git\Ninject\Ninject\src\ninject.test\Unit\ActivationCacheTests.cs:line 72
    [xUnit.net 00:00:02.2209958]     Ninject.Tests.Unit.CacheTests.WhenPruneIsCalled.CollectedScopeInstancesAreRemoved [FAIL]

(vs code, .net core 2, win 10)


So I've downloaded the source code from (https://github.com/ninject/Ninject/tree/3.3.1) and looked into Ninject.csproj:

    <TargetFrameworks>netstandard2.0;net45</TargetFrameworks>

and into Ninject.Test.csproj:

    <TargetFramework>net452</TargetFramework>


Looks like test project did not compiled for .netstandard2.0 and tests are not guards us from any threat in .net core runtime. 

So, my question: is ninject 3.3.1 production-ready for .net core 2? (at least as ninject 3.2.x for .net framework)

Second question: what extensions are adapted for .net core 2? is there a place where user can read this?

Third question: does the maintainers have any long-term plans to support .net core and other runtimes? Please clarify.

Sorry for poor English and thanks for the comment.

**Comment by scott-xu** [comment]
3.3.1 is production ready for .net core 2. Regarding Ninject.Extensions.Factory, there's no difference between net45 and netstandard2.0. Unit test with net452 is enough.
If you found any issue, please reproduce with the failing unit test.

**Comment by scott-xu** [comment]
Could you please file defect about Ninject in Ninject repo?

**Comment by lsoft** [comment]
> Could you please file defect about Ninject in Ninject repo?

Sorry, @scott-xu  I don't understand this phrase. What I could? Put a complete defect list to ninject repository in form of unit tests?

> If you found any issue, please reproduce with the failing unit test.

I've found about 5 issues with **existing** tests. There issues highlights differencies between .net framework and .net core in different aspects.
For example: WeakReferences+GC tests fails (look above). I guess it happens because of differencies in garbage collection implementation between .net core and .net framework. (maybe not)
But I don't know these differencies are important or irrelevant. You're said: it's production ready. But some test are red (on my computer)! Unclear how there facts corresponds with each other.

Can I get source from (https://github.com/ninject/Ninject/tree/3.3.1), adapt it for vs code, take a list of red tests and put it here? is it useful?

**Comment by scott-xu** [comment]
Please try again.

**Comment by scott-xu** [comment]
refer https://github.com/ninject/Ninject/commit/564bb54c9f43c8931a8e9cdf57c1bee1fed2c71f

**Comment by lsoft** [comment]
The key is <Optimize>true</Optimize> yeah...
They all are green now. thank you!
