### ISSUE TITLE
Castle.Core version 4.0 is not compatible with nuget package

### ISSUE THREAD

**Issue by rathkopf** [ninject/Ninject.Extensions.Factory#36]
I am unable to update Castle.Core nuget package because Ninject.Extensions.Factory references Castle.Core versions < 4.0.0.

Is this a legitimate issue, or could the package be updated so that castle.core will update?

**Comment by x2764tech** [comment]
I've cloned the repo, and I think `Castle.Core` can safely be updated to `4.1.0.0` - I don't understand Nant enough to figure out why the `.Net 4.5 CF` target isn't compiling.

**Comment by rvdroer** [comment]
We also are dependent on Castle.Core > 4.0.0.
Are there any plans to update the reference on this extention?

**Comment by alberto-chiesa** [comment]
Bumping this. In our case the conflict comes from `Moq`.
Simply updating the dependency works, but probaly breaks some platform.

**Comment by scott-xu** [comment]
Should be fixed in 3.3.0
