### ISSUE TITLE
New NuGet release?

### ISSUE THREAD

**Issue by pergardebrink** [ninject/Ninject.Extensions.Factory#51]
Hi,

I have problems with Lazy in .NET Core, which is fixed by #42 as far as I can see (which we currently have a fix that replaces the LazyConstructorScorer with a copy of the one in #42)

Is there any plans to push a new release out with the latest code? Is there anything I can do to help out to make that happen?

**Comment by scott-xu** [comment]
v3.3.3 released just now.

**Comment by pergardebrink** [comment]
Perfect! 

Thank you very much for helping out!

**Comment by pergardebrink** [comment]
Btw, is there a delay until NuGet makes it available for download?

I should probably wait until monday anyways, but was just so happy to be able to remove the workaround we have.. ;)

**Comment by scott-xu** [comment]
It should be listed in NuGet just now.

Regards,
Scott
发自我的 iPhone

在 2020年8月30日，22:39，Per Gårdebrink <notifications@github.com> 写道：

﻿

Btw, is there a delay until NuGet makes it available for download?

I should probably wait until monday anyways, but was just so happy to be able to remove the workaround we have.. ;)
